/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { BadgeDef, PresetSeed } from './types';

export const PRESET_SEEDS: PresetSeed[] = [
  {
    type: 'Neem',
    emoji: '🌳',
    enName: 'Neem (नीम)',
    hiName: 'नीम (Neem)',
    enDesc: 'The miraculous air-purifying tree known for its powerful antibacterial properties.',
    hiDesc: 'हवा को शुद्ध करने वाला चमत्कारी पेड़ जो अपने जीवाणुरोधी गुणों के लिए प्रसिद्ध है।',
    category: 'Medicinal',
  },
  {
    type: 'Holy Tulsi',
    emoji: '🌿',
    enName: 'Holy Tulsi (तुलसी)',
    hiName: 'पवित्र तुलसी (Tulsi)',
    enDesc: 'Revered ayurvedic healing herb found in traditional Indian courtyards.',
    hiDesc: 'पारंपरिक भारतीय आंगनों में पाया जाने वाला पूजनीय आयुर्वेदिक और औषधीय पौधा।',
    category: 'Sacred',
  },
  {
    type: 'Mogra',
    emoji: '💮',
    enName: 'Mogra / Jasmine (मोगरा)',
    hiName: 'मोगरा (Mogra)',
    enDesc: 'Intensely fragrant white blossoms used for festivals and natural perfume.',
    hiDesc: 'गहन सुगंध वाले सफेद फूल जिनका उपयोग त्योहारों और प्राकृतिक इत्र के लिए होता है।',
    category: 'Flowering',
  },
  {
    type: 'Genda',
    emoji: '🌼',
    enName: 'Genda / Marigold (गेंदा)',
    hiName: 'गेंदा (Genda)',
    enDesc: 'Cheerful bright orange floral blooms used in festive entrance garlands.',
    hiDesc: 'उत्सव की मालाओं में उपयोग किए जाने वाले चमकीले नारंगी रंग के सुंदर फूल।',
    category: 'Flowering',
  },
  {
    type: 'Aam',
    emoji: '🥭',
    enName: 'Mango / Aam (आम)',
    hiName: 'आम का पेड़ (Aam)',
    enDesc: 'The King of Fruits! Grows into a mighty shade-giving tree with sweet summer mangoes.',
    hiDesc: 'फलों का राजा! गर्मियों में मीठे आम और घनी छाया देने वाला विशाल पेड़।',
    category: 'Treeline',
  },
  {
    type: 'Amla',
    emoji: '🟢',
    enName: 'Amla / Gooseberry (आंवला)',
    hiName: 'आंवला (Amla)',
    enDesc: 'Superfood tree bearing round sour fruits packed with immunity-boosting Vitamin C.',
    hiDesc: 'प्रतिरोधक क्षमता बढ़ाने वाले विटामिन सी से भरपूर खट्टे फल देने वाला कल्याणकारी पेड़।',
    category: 'Medicinal',
  },
  {
    type: 'Bargad',
    emoji: '🌳',
    enName: 'Bargad / Banyan (बरगद)',
    hiName: 'बरगद / वटवृक्ष (Bargad)',
    enDesc: 'The National Tree of India, spreading grand aerial roots representing eternal life.',
    hiDesc: 'भारत का राष्ट्रीय वृक्ष, जिसकी लटकती जड़ें शाश्वत जीवन का प्रतिनिधित्व करती हैं।',
    category: 'Sacred',
  },
  {
    type: 'Peepal',
    emoji: '🌱',
    enName: 'Peepal / Sacred Fig (पीपल)',
    hiName: 'पीपल (Peepal)',
    enDesc: 'Highly revered leafy tree releasing pure oxygen 24 hours a day to clear local air.',
    hiDesc: 'चौबीसों घंटे शुद्ध ऑक्सीजन प्रदान करने वाला अत्यंत पूजनीय और विशाल वृक्ष।',
    category: 'Sacred',
  },
  {
    type: 'Gudhal',
    emoji: '🌺',
    enName: 'Gudhal / Hibiscus (गुड़हल)',
    hiName: 'गुड़हल (Gudhal)',
    enDesc: 'Striking red hibiscus flowers that nurture butterflies and benefit hair health.',
    hiDesc: 'खूबसूरत लाल फूल जो तितलियों को आकर्षित करते हैं और बालों के स्वास्थ्य के लिए उत्तम हैं।',
    category: 'Flowering',
  },
  {
    type: 'Aloe Vera',
    emoji: '🌵',
    enName: 'Aloe Vera / Ghritkumari',
    hiName: 'एलोवेरा (Aloe Vera)',
    enDesc: 'Low maintenance cooling succulent filled with soothing skin healing gel.',
    hiDesc: 'त्वचा को ठंडक पहुंचाने वाले और घाव भरने वाले जेल से भरपूर एक रसीला औषधीय पौधा।',
    category: 'Medicinal',
  },
  {
    type: 'Ashwagandha',
    emoji: '🌾',
    enName: 'Ashwagandha (अश्वगंधा)',
    hiName: 'अश्वगंधा (Ashwagandha)',
    enDesc: 'A premium stress-busting herbal root famous in ancient ayurvedic formulations.',
    hiDesc: 'प्राचीन आयुर्वेदिक औषधियों में प्रसिद्ध तनाव दूर करने वाली एक चमत्कारी बूटी।',
    category: 'Medicinal',
  },
  {
    type: 'Haldi',
    emoji: '🍠',
    enName: 'Turmeric / Haldi (हल्दी)',
    hiName: 'हल्दी (Haldi)',
    enDesc: 'Golden underground root used in daily cooking and credited with intense anti-septic power.',
    hiDesc: 'दैनिक भोजन में उपयोग होने वाली सुनहरी जड़ जो अपने एंटी-सेप्टिक गुणों के लिए जानी जाती है।',
    category: 'Medicinal',
  },
  {
    type: 'Kamal',
    emoji: '🪷',
    enName: 'Kamal / Indian Lotus (कमल)',
    hiName: 'कमल (Kamal)',
    enDesc: 'Indias national flower blooming gracefully in freshwater school eco-ponds.',
    hiDesc: 'कीचड़ में भी खिलने वाला भारत का राष्ट्रीय फूल जो तालाबों की शोभा बढ़ाता है।',
    category: 'Flowering',
  },
  {
    type: 'Champa',
    emoji: '🌼',
    enName: 'Champa / Plumeria (चंपा)',
    hiName: 'चंपा (Champa)',
    enDesc: 'Creamy white petals with exotic sweet aroma, commonly grown around tranquil temples.',
    hiDesc: 'मीठी और मनमोहक सुगंध वाले क्रीम रंग के फूल जो मंदिरों के पास लगाए जाते हैं।',
    category: 'Flowering',
  },
  {
    type: 'Parijat',
    emoji: '💮',
    enName: 'Parijat / Night Jasmine (पारिजात)',
    hiName: 'पारिजात (Parijat)',
    enDesc: 'Divine celestial flower with orange stems that drop naturally at dawn.',
    hiDesc: 'नारंगी डंडी वाले दिव्य और चमत्कारी फूल जो भोर में अपने आप झड़ जाते हैं।',
    category: 'Sacred',
  },
  {
    type: 'Palash',
    emoji: '🔥',
    enName: 'Palash / Flame of Forest (पलाश)',
    hiName: 'पलाश (Palash)',
    enDesc: 'Bright fiery orange-red flowers that blaze in spring and yield organic dyes.',
    hiDesc: 'वसंत ऋतु में जंगल की आग की तरह दहकने वाले फूल जो प्राकृतिक रंग बनाने के काम आते हैं।',
    category: 'Flowering',
  },
  {
    type: 'Gulmohar',
    emoji: '🌿',
    enName: 'Gulmohar (गुलमोहर)',
    hiName: 'गुलमोहर (Gulmohar)',
    enDesc: 'Features magnificent clusters of red-orange leaves lining school footpaths.',
    hiDesc: 'स्कूल के रास्तों के किनारे लाल और नारंगी फूलों की शानदार छटा बिखेरने वाला पेड़।',
    category: 'Treeline',
  },
  {
    type: 'Amaltas',
    emoji: '🟡',
    enName: 'Amaltas / Golden Shower (अमलतास)',
    hiName: 'अमलतास (Amaltas)',
    enDesc: 'Stunning yellow cascading blooms that light up dry Indian summer days.',
    hiDesc: 'पीले फूलों की शानदार लटकती लड़ियों वाला पेड़ जो कड़ी गर्मियों में खिलता है।',
    category: 'Treeline',
  },
  {
    type: 'Kadi Patta',
    emoji: '🍃',
    enName: 'Curry Leaves / Kadi Patta',
    hiName: 'कढ़ी पत्ता (Kadi Patta)',
    enDesc: 'Fragrant aromatic seasoning herb essential for south Indian food tempering.',
    hiDesc: 'दक्षिण भारतीय व्यंजनों को सुगंध और सोंधा स्वाद देने वाला खुशबूदार पौधा।',
    category: 'Veggies/Herbs',
  },
  {
    type: 'Pudina',
    emoji: '🌱',
    enName: 'Pudina / Mint (पुदीना)',
    hiName: 'पुदीना (Pudina)',
    enDesc: 'Zesty cooling green leaves used to prepare delicious summer juices and chutneys.',
    hiDesc: 'गर्मियों में ठंडक देने वाली स्वादिष्ट चटनी और शरबत बनाने के काम आने वाली पत्तियां।',
    category: 'Veggies/Herbs',
  },
  {
    type: 'Nimbu',
    emoji: '🍋',
    enName: 'Lemon / Nimbu (नींबू)',
    hiName: 'नींबू (Nimbu)',
    enDesc: 'Popular small tree producing juicy sour yellow lemons to beat high heat.',
    hiDesc: 'गर्मियों में ताजगी देने वाला खट्टा-मीठा पीला नींबू पैदा करने वाला छोटा कांटेदार पेड़।',
    category: 'Veggies/Herbs',
  },
  {
    type: 'Jamun',
    emoji: '🍇',
    enName: 'Jamun / Black Plum (जामुन)',
    hiName: 'जामुन (Jamun)',
    enDesc: 'Deep purple summer berries that color your tongue and help control blood sugar.',
    hiDesc: 'जीभ को बैंगनी रंग में रंगने वाले कषाय मीठे फल जो सेहत के लिए अत्यंत गुणकारी हैं।',
    category: 'Treeline',
  },
  {
    type: 'Anar',
    emoji: '🍎',
    enName: 'Pomegranate / Anar (अनार)',
    hiName: 'अनार (Anar)',
    enDesc: 'Beautiful red fruit containing juicy ruby-like seeds that are rich in iron.',
    hiDesc: 'आयरन से भरपूर चमकदार लाल दानों वाला फल देने वाला लोकप्रिय बगीचा वृक्ष।',
    category: 'Veggies/Herbs',
  },
  {
    type: 'Amrood',
    emoji: '🍏',
    enName: 'Guava / Amrood (अमरूद)',
    hiName: 'अमरूद (Amrood)',
    enDesc: 'Crunchy green backyard fruit with white/pink pulp, best enjoyed with spices.',
    hiDesc: 'नमक-मिर्च लगाकर खाया जाने वाला बच्चों का पसंदीदा स्वादिष्ट और सुलभ अमरुद।',
    category: 'Veggies/Herbs',
  },
  {
    type: 'Shami',
    emoji: '🌿',
    enName: 'Shami (शमी)',
    hiName: 'शमी का पौधा (Shami)',
    enDesc: 'Resilient and sacred dry-climate shrub praised for bringing good fortune.',
    hiDesc: 'कठिन मौसम में भी जीवित रहने वाला पूजनीय पौधा जो सौभाग्य और समृद्धि लाता है।',
    category: 'Sacred',
  },
  {
    type: 'Sagwan',
    emoji: '🪵',
    enName: 'Teak / Sagwan (सगवान)',
    hiName: 'सगवान (Sagwan)',
    enDesc: 'The king of indian timbers generating exceptionally strong, premium wood.',
    hiDesc: 'मजबूत और टिकाऊ लकड़ी के लिए प्रसिद्ध भारत का सबसे मुख्य वनस्पति पेड़।',
    category: 'Treeline',
  },
  {
    type: 'Chandan',
    emoji: '🪵',
    enName: 'Sandalwood / Chandan (चंदन)',
    hiName: 'चंदन (Chandan)',
    enDesc: 'Incredible fragrant heartwood used for cooling sandalwood paste and aroma.',
    hiDesc: 'ठंडक और दिव्य सुगंध देने वाली बहुमूल्य लकड़ी का अत्यंत पूजनीय औषधीय पेड़।',
    category: 'Sacred',
  },
  {
    type: 'Rudraksha',
    emoji: '📿',
    enName: 'Rudraksha (रुद्राक्ष)',
    hiName: 'रुद्राक्ष का पेड़ (Rudraksha)',
    enDesc: 'Sacred beads tree whose seeds are valued for mental clarity and peaceful state.',
    hiDesc: 'मानसिक शांति और एकाग्रता के लिए उपयोग होने वाली प्राकृतिक मनकों वाला पवित्र पेड़।',
    category: 'Sacred',
  },
  {
    type: 'Bel',
    emoji: '🍏',
    enName: 'Bel / Wood Apple (बेल)',
    hiName: 'बेलपत्र / श्रीफल (Bel)',
    enDesc: 'Medicinal tree whose three-lobed leaves are sacred, yielding thick summer drink pulp.',
    hiDesc: 'तीन पत्तों वाला पूजनीय पेड़ जिसका फल गर्मियों में पेट को परम शीतलता देता है।',
    category: 'Sacred',
  },
  {
    type: 'Ashoka',
    emoji: '🌲',
    enName: 'Ashoka Tree (अशोक)',
    hiName: 'अशोक वृक्ष (Ashoka)',
    enDesc: 'Tall and slender evergreen tree known to block environmental noise pollution.',
    hiDesc: 'बिना किसी शोक वाला सीधा हरा-भरा पेड़ जो खेतों और रास्तों में ध्वनि प्रदूषण को रोकता है।',
    category: 'Sacred',
  },
  {
    type: 'Giloy',
    emoji: '🌿',
    enName: 'Giloy / Amrita (गिलोय)',
    hiName: 'गिलोय बेल (Giloy)',
    enDesc: 'Vigorous heart-leaved climbing vine that naturally boosts immunity and plates.',
    hiDesc: 'पान जैसी पत्तियों वाली प्राकृतिक लता जो बुखार को मिटाकर रोग प्रतिरोधक क्षमता बढ़ाती है।',
    category: 'Medicinal',
  },
  {
    type: 'Brahmi',
    emoji: '🌱',
    enName: 'Brahmi (ब्राह्मी)',
    hiName: 'ब्राह्मी (Brahmi)',
    enDesc: 'A tiny moisture-loving creeping herb celebrated for improving concentration and memory.',
    hiDesc: 'मस्तिष्क की कार्यक्षमता और याददाश्त बढ़ाने वाली पानी के पास उगने वाली कोमल बूटी।',
    category: 'Medicinal',
  },
  {
    type: 'Baans',
    emoji: '🎋',
    enName: 'Bamboo / Baans (बांस)',
    hiName: 'बांस (Baans)',
    enDesc: 'Super-fast growing grass capturing immense amounts of carbon from daily air.',
    hiDesc: 'धरती पर सबसे तेजी से बढ़ने वाली घास जो हवा से भारी मात्रा में कार्बन सोखती है।',
    category: 'Treeline',
  },
  {
    type: 'Mirchi',
    emoji: '🌶️',
    enName: 'Chili / Mirchi (मिर्च)',
    hiName: 'हरी मिर्च (Mirchi)',
    enDesc: 'Spicy and decorative backyard plant yielding pungent red and green wonders.',
    hiDesc: 'भोजन में तीखापन और चटपटा स्वाद लाने वाला आसानी से उगने वाला घरेलू पौधा।',
    category: 'Veggies/Herbs',
  },
  {
    type: 'Dhania',
    emoji: '🌿',
    enName: 'Coriander / Dhania (धनिया)',
    hiName: 'हरा धनिया (Dhania)',
    enDesc: 'Aromatic soft leafy herb seeded for instant coriander garnishing and seasoning.',
    hiDesc: 'हर डिश का स्वाद बढ़ाने वाली और झटपट उगने वाली खुशबूदार कोमल पत्तियां।',
    category: 'Veggies/Herbs',
  },
  {
    type: 'Methi',
    emoji: '🌱',
    enName: 'Fenugreek / Methi (मेथी)',
    hiName: 'मेथी (Methi)',
    enDesc: 'Healthy greens cooked as iron-rich winters vegetables with slight bitter-sweetness.',
    hiDesc: 'सर्दियों में उगाई जाने वाली कड़वाहट लिए हुए बेहद स्वास्थ्यवर्धक हरी पत्तेदार सब्जी।',
    category: 'Veggies/Herbs',
  },
  {
    type: 'Papita',
    emoji: '🍈',
    enName: 'Papaya / Papita (पपीता)',
    hiName: 'पपीता (Papita)',
    enDesc: 'Quick growing upright tree giving large sweet orange digested aid fruits.',
    hiDesc: 'तेजी से बढ़ने वाला अकेला तने का फलदार पेड़ जो पेट के लिए अमृत समान फल देता है।',
    category: 'Veggies/Herbs',
  },
  {
    type: 'Chikoo',
    emoji: '🟤',
    enName: 'Sapodilla / Chikoo (चीकू)',
    hiName: 'चीकू (Chikoo)',
    enDesc: 'Sweet sandy-textured brown fruit with a delicious brown honey taste.',
    hiDesc: 'बालू जैसी बनावट और शहद जैसी मिठास वाला भूरे रंग का स्वादिष्ट बगीचा फल।',
    category: 'Veggies/Herbs',
  },
  {
    type: 'Imli',
    emoji: '🫘',
    enName: 'Tamarind / Imli (इमली)',
    hiName: 'इमली का पेड़ (Imli)',
    enDesc: 'Enormous long-living shade tree producing ultra tangy-sour culinary brown pods.',
    hiDesc: 'खट्टी-मीठी चटनी और दाल का स्वाद बढ़ाने वाली खट्टी फलियां देने वाला विशाल छायादार पेड़।',
    category: 'Treeline',
  },
  {
    type: 'Nariyal',
    emoji: '🌴',
    enName: 'Coconut / Nariyal (नारियल)',
    hiName: 'नारियल पेड़ / कल्पवृक्ष',
    enDesc: 'Towering tropical palm tree where every single branch, leaf and fruit is valuable.',
    hiDesc: 'तटीय हवाओं को सहने वाला पेड़ जिसके फल का मीठा पानी और गिरी अमृत समान है।',
    category: 'Sacred',
  },
  {
    type: 'Yellow Gudhal',
    emoji: '🌻',
    enName: 'Yellow Hibiscus (गुड़हल पीला)',
    hiName: 'पीला गुड़हल (Gudhal)',
    enDesc: 'Sun-worshiping golden hibiscus flower that attracts friendly honey bees and butterflies.',
    hiDesc: 'सुनहरे रंग का फूल जो मधुमक्खियों और रंग-बिरंगी तितलियों को बगीचे में बुलाता है।',
    category: 'Flowering',
  },
  {
    type: 'Kaner',
    emoji: '🏵️',
    enName: 'Kaner / Oleander (कनेर)',
    hiName: 'पनेर / कनेर (Kaner)',
    enDesc: 'Extremely tough summer plant producing bright pink or yellow floral bunches.',
    hiDesc: 'तेज धूप और सूखे में भी खिलने वाला मजबूत पीला अथवा गुलाबी फूलों का सजावटी पौधा।',
    category: 'Flowering',
  },
  {
    type: 'Shankhpushpi',
    emoji: '🌀',
    enName: 'Shankhpushpi (शंखपुष्पी)',
    hiName: 'शंखपुष्पी (Shankhpushpi)',
    enDesc: 'Stunning bright blue bell flowers valued in Ayurveda as a supreme brain memory tonic.',
    hiDesc: 'नीले रंग के शंख जैसे दिखने वाले फूल जो बच्चों की एकाग्रता बढ़ाने के लिए जाने जाते हैं।',
    category: 'Medicinal',
  },
  {
    type: 'Lemon Grass',
    emoji: '🌾',
    enName: 'Lemongrass (लेमन ग्रास)',
    hiName: 'लेमन ग्रास (Lemongrass)',
    enDesc: 'Citrusy aromatic grass perfect for brewing healthy immunity-boosting morning teas.',
    hiDesc: 'नींबू जैसी सुगंध वाली अद्भुत घास जिसके पत्तों की चाय सेहत और पाचन को दुरुस्त करती है।',
    category: 'Medicinal',
  },
  {
    type: 'Ram Tulsi',
    emoji: '🌿',
    enName: 'Ram Tulsi (राम तुलसी)',
    hiName: 'राम तुलसी (Ram Tulsi)',
    enDesc: 'Light green, clove-scented holy basil with highly soothing herbal steam benefits.',
    hiDesc: 'हल्की हरी पत्तियों वाली मीठी सुगंध की तुलसी जो सर्दी और कफ को प्राकृतिक रूप से मिटाती है।',
    category: 'Sacred',
  },
  {
    type: 'Shyama Tulsi',
    emoji: '🪻',
    enName: 'Shyama Tulsi (कृष्णा तुलसी)',
    hiName: 'श्यामा तुलसी (Shyama Tulsi)',
    enDesc: 'Dark purple leaves filled with strong antioxidant adaptogens to boost immune power.',
    hiDesc: 'गहरे बैंगनी रंग की तुलसी जो अत्यधिक तीव्र औषधीय गुणों और शक्ति से भरपूर है।',
    category: 'Sacred',
  },
  {
    type: 'Ajwain',
    emoji: '🍃',
    enName: 'Carom / Ajwain (अजवायन)',
    hiName: 'अजवायन पौधा (Ajwain)',
    enDesc: 'Fuzzy succulent textured leaves that release carom aroma and relieve stomach aches.',
    hiDesc: 'मखमली पत्तियों वाला पौधा जिसकी खुशबू अजवायन जैसी होती है और पेट को आराम देती है।',
    category: 'Veggies/Herbs',
  },
  {
    type: 'Sadabahar',
    emoji: '🌸',
    enName: 'Periwinkle / Sadabahar',
    hiName: 'सदाबहार (Sadabahar)',
    enDesc: 'Ever-blooming pink and white flowers that flourish without demanding extra care.',
    hiDesc: 'हर मौसम में खिलने वाले गुलाबी-सफेद फूल जो शून्य देखभाल में भी मुस्कुराते हैं।',
    category: 'Flowering',
  },
  {
    type: 'Bougainvillea',
    emoji: '🌺',
    enName: 'Paper Flower / Bougainvillea',
    hiName: 'बोगनविलिया (Bougainvillea)',
    enDesc: 'Thorny colorful climber that completely covers school gates with pink paper-thin blooms.',
    hiDesc: 'कागज जैसे गुलाबी फूलों से स्कूल के गेट को सजाने वाली एक बेहद साहसी कांटेदार लता।',
    category: 'Flowering',
  },
  {
    type: 'Elaichi',
    emoji: '🌱',
    enName: 'Cardamom / Elaichi (इलायची)',
    hiName: 'इलायची पौधा (Elaichi)',
    enDesc: 'The Queen of Spices, grows in moist shade with highly aromatic giant leafy stems.',
    hiDesc: 'मसालों की रानी! छाया और नमी में उगने वाला इलायची का सुगन्धित और मनोहर पौधा।',
    category: 'Veggies/Herbs',
  },
];

export const BADGE_DETAILS: { [id: string]: BadgeDef } = {
  'first-plant': {
    id: 'first-plant',
    en: { name: 'Green Starter 🌱', desc: 'Planted your very first environmental seed!' },
    hi: { name: 'हरित प्रारंभ 🌱', desc: 'अपना पहला पर्यावरण बीज बोया!' },
    emoji: '🌱',
    color: 'bg-emerald-100 border-emerald-400 text-emerald-800',
  },
  'water-master': {
    id: 'water-master',
    en: { name: 'Water Hero 💧', desc: 'Watered your plant 3 times with love.' },
    hi: { name: 'जल रक्षक 💧', desc: 'अपने पौधे को प्यार से 3 बार पानी दिया।' },
    emoji: '💧',
    color: 'bg-blue-100 border-blue-400 text-blue-800',
  },
  'sun-lover': {
    id: 'sun-lover',
    en: { name: 'Sun Chaser ☀️', desc: 'Gave your plant healthy sunlight 3 times.' },
    hi: { name: 'धूप प्रेमी ☀️', desc: 'अपने पौधे को 3 बार स्वस्थ धूप दी।' },
    emoji: '☀️',
    color: 'bg-amber-100 border-amber-400 text-amber-800',
  },
  'fully-grown': {
    id: 'fully-grown',
    en: { name: 'Master Gardener 🌳', desc: 'Brought at least one plant to 100% full growth!' },
    hi: { name: 'मास्टर माली 🌳', desc: 'कम से कम एक पौधे को 100% पूर्ण विकास तक पहुँचाया!' },
    emoji: '🌳',
    color: 'bg-green-100 border-green-500 text-green-800',
  },
  'principal-star': {
    id: 'principal-star',
    en: { name: 'Eco Champion 🎖️', desc: 'Awarded by your teacher/principal for dedication!' },
    hi: { name: 'इको चैंपियन 🎖️', desc: 'समर्पण के लिए आपके शिक्षक/प्रधानाचार्य द्वारा पुरस्कृत!' },
    emoji: '🎖️',
    color: 'bg-yellow-100 border-yellow-500 text-yellow-800',
  },
  'green-hero': {
    id: 'green-hero',
    en: { name: 'Earth Savior 🌍', desc: 'Granted for keeping multiple plants healthy.' },
    hi: { name: 'धरती रक्षक 🌍', desc: 'कई पौधों को स्वस्थ रखने के लिए प्रदान किया गया।' },
    emoji: '🌍',
    color: 'bg-sky-100 border-sky-400 text-sky-800',
  },
};

export const ECO_TIPS = {
  en: [
    'Trees give us pure oxygen to breathe. Let\'s grow one together!',
    'Watering plants early morning saves water from disappearing into the air!',
    'Every tree planted helps clean the dirty smoke in our sky.',
    'Healthy soil needs organic compost. Feeding your plant helps it blossom faster!',
    'Did you know? A single tree can be home to hundreds of friendly birds and butterflies! 🦋',
    'Say NO to plastic bags and use a cloth bag to protect Earth\'s soil!',
  ],
  hi: [
    'पेड़ हमें सांस लेने के लिए शुद्ध ऑक्सीजन देते हैं। आइए मिलकर एक पेड़ उगाएं!',
    'सुबह जल्दी पौधों को पानी देने से पानी हवा में उड़ने से बचता है!',
    'लगाया गया हर पेड़ हमारे आसमान में गंदे धुएं को साफ करने में मदद करता है।',
    'स्वस्थ मिट्टी को जैविक खाद की आवश्यकता होती है। पौधे को खाद खिलाने से वह तेजी से खिलता है!',
    'क्या आप जानते हैं? एक अकेला पेड़ सैकड़ों मित्र पक्षियों और तितलियों का घर हो सकता है! 🦋',
    'पृथ्वी की मिट्टी की रक्षा के लिए प्लास्टिक की थैलियों को ना कहें और कपड़े के थैले का उपयोग करें!',
  ],
};

export const TRANSLATIONS = {
  en: {
    nav_title: 'Eco-Planter',
    nav_sub: 'World Environment Day',
    lang_btn: 'हिन्दी',
    hero_title: 'My school Garden',
    hero_sub: 'Plant a seed today, grow a greener tomorrow!',
    btn_register: 'Join Green Mission (New Student) 🌱',
    btn_login: 'Student Login 🔑',
    btn_admin: 'Teacher & Admin Panel 🧑‍🏫',
    reg_back: 'Back',
    reg_title: 'Join Eco-Planter 🌱',
    reg_sub: 'Create your personal school eco account',
    lbl_reg_name: 'Your Full Name 👤',
    lbl_reg_class: 'Which Class do you study in? 🏫',
    lbl_reg_sec: 'Select your Section / Stream 📚',
    lbl_reg_pass: 'Create simple Password 🔒',
    btn_magic: '✨ Auto Fill',
    btn_reg_submit: 'Generate Account Credentials',
    reg_pass_note: 'Tip: Keep it short like a 4-digit number or a simple word',
    succ_title: 'Account Created Successfully! 🎉',
    succ_sub: 'Remember these details to login later!',
    succ_lbl_name: 'Full Name',
    succ_lbl_class: 'Class & Section',
    succ_lbl_id: 'Login Student ID',
    succ_lbl_pass: 'Password',
    succ_btn_go: 'Go to My Garden Dashboard',
    succ_btn_copy: 'Copy details to clipboard',
    login_back: 'Back',
    login_title: 'Student Login',
    login_sub: 'Enter credentials to open your plant journal',
    lbl_login_id: 'Your Student ID 🎫',
    lbl_login_pass: 'Your Password 🔒',
    btn_login_submit: 'Enter Garden Dashboard',
    admin_login_back: 'Back',
    admin_title: 'Teacher Portal',
    admin_sub: 'Access student details and award eco-points',
    lbl_admin_pass: 'Admin Password 🔑',
    btn_admin_submit: 'Verify Credentials',
    dash_greeting: 'Welcome, Planter Champion!',
    dash_motto: 'Thank you for taking care of nature on World Environment Day! 💚',
    dash_stat_level: 'Planter Level',
    dash_stat_xp: 'Total XP',
    dash_garden_title: 'My Beautiful Garden',
    dash_btn_seed: 'Plant a New Seed',
    empty_plant_title: 'Your Garden is Empty!',
    empty_plant_desc: 'Let\'s start your environmental mission by planting your very first seed! Click the button above to begin.',
    empty_plant_btn: 'Plant Your First Seed Now',
    dash_badges: 'My Earned Badges',
    fact_title: 'Did You Know?',
    fact_btn: 'Next Tip',
    leaderboard_title: 'Top Planters in School',
    admin_dash_title: 'World Environment Day - School Hub',
    admin_dash_sub: 'Monitor student registrations, view planted trees, and award bonus stars!',
    adm_stat_students: 'Total Planters',
    adm_stat_plants: 'Trees Planted',
    adm_stat_actions: 'Actions Logged',
    adm_dir_title: 'Student Directory',
    filter_all_classes: 'All Classes',
    th_student: 'Student details',
    th_class: 'Class',
    th_plants: 'Planted Trees',
    th_points: 'Green Points (XP)',
    th_action: 'Manage & Reward',
    adm_no_stud_title: 'No matching students found',
    adm_no_stud_desc: 'Either no one has registered, or your filter is too strict.',
    adm_class_stand: 'Class Performance Standings',
    teacher_tip_title: 'Teacher Coordinator Tip',
    teacher_tip_body: 'Click "Give Badge" or "Award XP" to instantly congratulate active environmental workers. They will see a celebration confetti surprise when they log in!',
    m_plant_title: 'Choose Your Environmental Seed',
    m_plant_sub: 'Each tree grows strong as you take care of it!',
    preset_sun: 'Sunflower',
    preset_sun_sub: 'Beautiful Yellow Flower',
    preset_tulsi: 'Holy Tulsi',
    preset_tulsi_sub: 'Healthy & Ayurvedic',
    preset_rose: 'Rose',
    preset_rose_sub: 'Smells Fantastic',
    preset_tomato: 'Tomato',
    preset_tomato_sub: 'Yummy Red Tomatoes',
    lbl_seed_nick: 'Give your plant a cute nickname! 🥰',
    m_plant_btn: 'Plant the Seed Now',
    act_water: 'Water',
    act_sun: 'Sunshine',
    act_feed: 'Compost',
    act_patience_tip: '💡 Tip: Keep taking care of your plant daily to watch it blossom!',
    adm_action_title: 'Teacher Action Command Centre',
    adm_lbl_points: 'Award Environmental Points (XP)',
    adm_lbl_badge: 'Grant Special Honor Badge',
    badge_star_name: 'Eco Champion',
    badge_hero_name: 'Earth Savior',
    adm_lbl_plants: 'Student Plant Collection',
    foot_title: 'Save Trees, Save Lives! 🍃',
    foot_sub: 'Created for schools globally to celebrate nature on World Environment Day.',
    foot_copy: 'Every action matters. Let\'s grow green together!',
    admin_logout_text: 'Exit Admin',
  },
  hi: {
    nav_title: 'इको-प्लांटर',
    nav_sub: 'विश्व पर्यावरण दिवस',
    lang_btn: 'English',
    hero_title: 'मेरा स्कूल बगीचा',
    hero_sub: 'आज एक बीज बोएं, आने वाले कल को स्वच्छ बनाएं!',
    btn_register: 'हरित मिशन से जुड़ें (नया छात्र) 🌱',
    btn_login: 'छात्र लॉगिन 🔑',
    btn_admin: 'शिक्षक एवं एडमिन पोर्टल 🧑‍🏫',
    reg_back: 'पीछे जाएं',
    reg_title: 'इको-प्लांटर से जुड़ें 🌱',
    reg_sub: 'अपना व्यक्तिगत स्कूल खाता बनाएं',
    lbl_reg_name: 'आपका पूरा नाम 👤',
    lbl_reg_class: 'आप किस कक्षा में पढ़ते हैं? 🏫',
    lbl_reg_sec: 'अपने सेक्शन / स्ट्रीम का चयन करें 📚',
    lbl_reg_pass: 'एक सरल पासवर्ड बनाएं 🔒',
    btn_magic: '✨ स्वतः भरें',
    btn_reg_submit: 'खाता विवरण तैयार करें',
    reg_pass_note: 'सुझाव: इसे छोटा रखें जैसे 4 अंकों का नंबर या एक आसान शब्द',
    succ_title: 'खाता सफलतापूर्वक बनाया गया! 🎉',
    succ_sub: 'अगली बार लॉगिन करने के लिए इन विवरणों को याद रखें!',
    succ_lbl_name: 'पूरा नाम',
    succ_lbl_class: 'कक्षा और अनुभाग',
    succ_lbl_id: 'लॉगिन स्टूडेंट आईडी',
    succ_lbl_pass: 'पासवर्ड',
    succ_btn_go: 'मेरे गार्डन डैशबोर्ड पर जाएं',
    succ_btn_copy: 'विवरण कॉपी करें',
    login_back: 'पीछे जाएं',
    login_title: 'छात्र लॉगिन',
    login_sub: 'अपने पौधे की डायरी खोलने के लिए क्रेडेंशियल दर्ज करें',
    lbl_login_id: 'आपकी स्टूडेंट आईडी 🎫',
    lbl_login_pass: 'आपका पासवर्ड 🔒',
    btn_login_submit: 'गार्डन डैशबोर्ड में प्रवेश करें',
    admin_login_back: 'पीछे जाएं',
    admin_title: 'शिक्षक पोर्टल',
    admin_sub: 'छात्रों के विवरण देखें और इको-पॉइंट्स दें',
    lbl_admin_pass: 'एडमिन पासवर्ड 🔑',
    btn_admin_submit: 'क्रेडेंशियल सत्यापित करें',
    dash_greeting: 'स्वागत है, प्लांटर चैंपियन!',
    dash_motto: 'विश्व पर्यावरण दिवस पर प्रकृति की देखभाल करने के लिए धन्यवाद! 💚',
    dash_stat_level: 'प्लांटर लेवल',
    dash_stat_xp: 'कुल एक्सपी (XP)',
    dash_garden_title: 'मेरा सुंदर बगीचा',
    dash_btn_seed: 'एक नया बीज बोएं',
    empty_plant_title: 'आपका बगीचा खाली है!',
    empty_plant_desc: 'अपना पहला बीज बोकर अपना पर्यावरण मिशन शुरू करें! शुरू करने के लिए ऊपर दिए गए बटन पर क्लिक करें।',
    empty_plant_btn: 'अभी अपना पहला बीज बोएं',
    dash_badges: 'मेरे अर्जित बैज',
    fact_title: 'क्या आप जानते हैं?',
    fact_btn: 'अगला सुझाव',
    leaderboard_title: 'स्कूल में शीर्ष प्लांटर्स',
    admin_dash_title: 'विश्व पर्यावरण दिवस - स्कूल हब',
    admin_dash_sub: 'छात्रों के पंजीकरण की निगरानी करें, लगाए गए पेड़ देखें, और बोनस अंक दें!',
    adm_stat_students: 'कुल छात्र',
    adm_stat_plants: 'लगाए गए पेड़',
    adm_stat_actions: 'दर्ज की गई क्रियाएं',
    adm_dir_title: 'छात्र निर्देशिका',
    filter_all_classes: 'सभी कक्षाएं',
    th_student: 'छात्र विवरण',
    th_class: 'कक्षा',
    th_plants: 'लगाए गए पेड़',
    th_points: 'ग्रीन पॉइंट (XP)',
    th_action: 'प्रबंधन और पुरस्कार',
    adm_no_stud_title: 'कोई मेल खाने वाला छात्र नहीं मिला',
    adm_no_stud_desc: 'या तो किसी ने पंजीकरण नहीं किया है, या आपका फ़िल्टर बहुत सख्त है।',
    adm_class_stand: 'कक्षा प्रदर्शन की स्थिति',
    teacher_tip_title: 'शिक्षक समन्वयक सुझाव',
    teacher_tip_body: 'सक्रिय पर्यावरण कार्यकर्ताओं को तुरंत बधाई देने के लिए "बैज दें" या "एक्सपी दें" पर क्लिक करें। लॉग इन करने पर उन्हें एक शानदार कंफ़ेटी सरप्राइज़ दिखेगा!',
    m_plant_title: 'अपना पर्यावरण बीज चुनें',
    m_plant_sub: 'जैसे-जैसे आप इसकी देखभाल करते हैं, हर पेड़ मजबूत होता जाता है!',
    preset_sun: 'सूरजमुखी',
    preset_sun_sub: 'सुंदर पीला फूल',
    preset_tulsi: 'पवित्र तुलसी',
    preset_tulsi_sub: 'स्वस्थ और आयुर्वेदिक',
    preset_rose: 'गुलाब',
    preset_rose_sub: 'शानदार खुशबू',
    preset_tomato: 'टमाटर',
    preset_tomato_sub: 'स्वादिष्ट लाल टमाटर',
    lbl_seed_nick: 'अपने पौधे को एक प्यारा उपनाम दें! 🥰',
    m_plant_btn: 'अभी बीज बोएं',
    act_water: 'पानी दें',
    act_sun: 'धूप दिखाएं',
    act_feed: 'खाद दें',
    act_patience_tip: '💡 सुझाव: अपने पौधे को खिलते हुए देखने के लिए रोजाना उसकी देखभाल करते रहें!',
    adm_action_title: 'शिक्षक कार्रवाई कमान केंद्र',
    adm_lbl_points: 'पर्यावरण अंक (XP) प्रदान करें',
    adm_lbl_badge: 'विशेष सम्मान बैज प्रदान करें',
    badge_star_name: 'इको चैंपियन',
    badge_hero_name: 'धरती रक्षक',
    adm_lbl_plants: 'छात्र का पौधा संग्रह',
    foot_title: 'पेड़ बचाओ, जीवन बचाओ! 🍃',
    foot_sub: 'विश्व पर्यावरण दिवस पर प्रकृति का जश्न मनाने के लिए वैश्विक स्तर पर स्कूलों के लिए बनाया गया।',
    foot_copy: 'हर कदम मायने रखता है। चलो साथ मिलकर हरियाली बढ़ाएं!',
    admin_logout_text: 'एडमिन से बाहर निकलें',
  },
};
